# src/report.py
import io, os
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from datetime import datetime

def compose_report(output_pdf_path, metadata, findings, images_dict):
    """
    Compose a structured, professional-style AI MRI Tumor report.

    Args:
        output_pdf_path (str): Path to save PDF.
        metadata (dict): case info, e.g. {'case_id': 'BraTS20_Training_001', 'age': '45'}
        findings (dict): contains 'summary', 'detailed', 'quantitative', 'explainability', 'recommendations'
        images_dict (dict): title->numpy image
    """
    c = canvas.Canvas(output_pdf_path, pagesize=A4)
    w, h = A4
    line_height = 16

    # -------------------------------
    # PAGE 1 — Header + Summary
    # -------------------------------
    # --- Header ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, h - 80, "MRI Brain Tumor Report – AI Assisted")

    c.setFont("Helvetica", 12)
    c.drawString(40, h - 110, f"Patient / Case: {metadata.get('case_id', '-')}")
    c.drawString(40, h - 130, f"Age: {metadata.get('age', '-')}")
    c.drawString(40, h - 150, f"Tumor Grade: {metadata.get('grade', '-')}")
    c.drawString(40, h - 170, f"Extent of Resection: {findings['quantitative'].get('Extent of Resection', '-')}")
    c.drawString(40, h - 190, f"Reported Survival: {findings['quantitative'].get('Reported Survival', '-')}")
    c.drawString(40, h - 210, f"Report generated by Dual-Modality Preop AI (MRI-only mode)")

    # Summary
    text = c.beginText(40, h - 300)
    text.setFont("Helvetica-Bold", 13)
    text.textLine("Summary of Findings:")
    text.setFont("Helvetica", 11)
    text.textLines(findings.get('summary', ''))
    c.drawText(text)

    # Quick quantitative overview
    y = h - 300
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Key Metrics")
    c.setFont("Helvetica", 11)
    metrics = findings.get('quantitative', {})
    for k, v in metrics.items():
        y -= line_height
        c.drawString(60, y, f"{k}: {v}")
    c.showPage()

    # -------------------------------
    # PAGE 2 — Detailed Findings
    # -------------------------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, h - 80, "Detailed Radiological Findings")

    text = c.beginText(40, h - 110)
    text.setFont("Helvetica", 11)
    text.textLines(findings.get('detailed', ''))
    c.drawText(text)

    # Quantitative metrics (table)
    y = h - 300
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Quantitative Metrics")
    c.setFont("Helvetica", 11)
    metrics = findings.get('quantitative', {})
    for k, v in metrics.items():
        y -= 16
        c.drawString(60, y, f"• {k}: {v}")


    # Explainability notes
    y -= 20
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Explainability Overview")
    y -= 20
    c.setFont("Helvetica", 11)
    for line in findings.get('explainability', '').split('\n'):
        c.drawString(60, y, line)
        y -= line_height

    # Recommendations
    y -= 30
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Recommendations")
    y -= 20
    c.setFont("Helvetica", 11)
    for line in findings.get('recommendations', '').split('\n'):
        c.drawString(60, y, line)
        y -= line_height
    c.showPage()

    # -------------------------------
    # PAGE 3 — Visual Results
    # -------------------------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, h - 80, "Images & Attention Maps")

    y = h - 120
    for title, img_arr in images_dict.items():
        buf = io.BytesIO()
        plt.imsave(buf, img_arr, cmap='gray', format='png', vmin=0, vmax=1)
        buf.seek(0)
        c.drawImage(ImageReader(buf), 40, y - 180, width=350, height=160)
        c.setFont("Helvetica", 12)
        c.drawString(410, y - 80, title)
        y -= 200
        if y < 150:
            c.showPage()
            y = h - 120

    # Disclaimer
    c.showPage()
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, h - 80, "Disclaimer")
    text = c.beginText(40, h - 110)
    text.setFont("Helvetica", 11)
    text.textLines(
        "This report was automatically generated using the Dual-Modality AI platform.\n"
        "It is intended for research and assistive use only and is not a substitute for a qualified radiologist’s interpretation.\n"
        "All diagnostic and treatment decisions should be confirmed by a medical professional."
    )
    c.drawText(text)

    c.save()
