# src/report.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import matplotlib.pyplot as plt
import io

def compose_report(output_pdf_path, metadata, findings, images_dict):
    c = canvas.Canvas(output_pdf_path, pagesize=A4)
    w, h = A4

    # Page 1: Title + summary
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, h-80, "MRI Brain Tumor Report - AI Assisted")
    c.setFont("Helvetica", 12)
    c.drawString(40, h-110, f"Patient / Case: {metadata.get('case_id','-')}")
    c.drawString(40, h-130, f"Age: {metadata.get('age','-')}, Report generated by Dual-Modality Preop AI (MRI-only mode)")
    # Summary box
    text = c.beginText(40, h-180)
    text.setFont("Helvetica", 11)
    text.textLines("SUMMARY:\n" + findings['summary'])
    c.drawText(text)

    # Page 2: Detailed findings, location, size
    c.showPage()
    c.setFont("Helvetica-Bold", 14); c.drawString(40, h-80, "Detailed Findings")
    text = c.beginText(40, h-110); text.setFont("Helvetica", 11)
    text.textLines(findings['detailed'])
    c.drawText(text)

    # Page 3: Images (segmentation + attention)
    c.showPage()
    c.setFont("Helvetica-Bold", 14); c.drawString(40, h-80, "Images & Attention Maps")
    y = h-120
    for title, img_arr in images_dict.items():
        # convert numpy img to bytes
        buf = io.BytesIO()
        plt.imsave(buf, img_arr, cmap='gray', format='png', vmin=0, vmax=1)
        buf.seek(0)
        c.drawImage(ImageReader(buf), 40, y-180, width=350, height=160)
        c.drawString(400, y-80, title)
        y -= 200
        if y < 120:
            c.showPage(); y = h-120
    c.save()
